name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: DockerHub
    env:
      TAG: $(date +%s)
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Docker Build and Tag
      run: docker build --load -t ${{ vars.REGISTRY_NAME }}:latest -t ${{ vars.REGISTRY_NAME }}:${{ env.TAG }} --target deploy .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push Docker image tags to Docker Hub
      run: |
        docker push ${{ vars.REGISTRY_NAME }}:latest
        docker push ${{ vars.REGISTRY_NAME }}:${{ env.TAG }}
        
