name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: DockerHub
    env:
      TAG: $(date +%s)
    steps:
    - uses: actions/checkout@v3
    - name: Docker Build and Tag
      run: |
        docker build . --file Dockerfile --tag ${{ vars.REGISTRY_NAME }}:latest
        docker build . --file Dockerfile --tag ${{ vars.REGISTRY_NAME }}:$GITHUB_SHA

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push Docker image tags to Docker Hub
      run: |
        docker push ${{ vars.REGISTRY_NAME }}:latest
        docker push ${{ vars.REGISTRY_NAME }}:$GITHUB_SHA
        
